apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtdenoise-training-dataset
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti

