apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dataset-prebatch
  labels:
    app:  dataset-prebatch
spec:
  selector:
    matchLabels:
      app: dataset-prebatch
  replicas: 1
  template:
    metadata:
      labels:
        app:  dataset-prebatch
    spec:
      containers:
      - name:  dataset-prebatch
        image:  saadam1n/prebatch
        command: ["/bin/sh", "-c", "python3 -u ./script.py /mnt/rtdenoise_dataset_tar_filtered/ /mnt/rtdenoise_dataset_filtered_prebatched/ 8 40 color albedo normal motionvec && echo Freaking finished && sleep 99999999"]
        resources:
          requests:
            cpu: "50"
            memory: 32Gi
          limits:
            cpu: "50"
            memory: 32Gi
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset_tar_filtered/
          name: rtdenoise-dataset-tar-filtered
        - mountPath: /mnt/rtdenoise_dataset_filtered_prebatched/
          name: rtdenoise-dataset-filtered-prebatched
      volumes:
          - name: rtdenoise-dataset-tar-filtered
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-tar-filtered
          - name: rtdenoise-dataset-filtered-prebatched
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-filtered-prebatched


