apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dataset-tartool
  labels:
    app:  dataset-tartool
spec:
  selector:
    matchLabels:
      app: dataset-tartool
  replicas: 1
  template:
    metadata:
      labels:
        app:  dataset-tartool
    spec:
      nodeSelector:
        nautilus.io/network: "100000"  
      containers:
      - name:  dataset-tartool
        image:  saadam1n/tartool
        command: ["/bin/sh", "-c", "python3 -u ./script.py /mnt/rtdenoise_dataset_tar_filtered/ /mnt/rtdenoise_dataset_tar_filtered/ && echo Freaking finished && sleep 99999999"]
        resources:
          requests:
            cpu: 64
            memory: 96Gi
          limits:
            cpu: 64
            memory: 96Gi
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset_tar_filtered/
          name: rtdenoise-dataset-tar-filtered
      volumes:
          - name: rtdenoise-dataset-tar-filtered
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-tar-filtered


