apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dataset-copier
  labels:
    app:  dataset-copier
spec:
  selector:
    matchLabels:
      app: dataset-copier
  replicas: 1
  template:
    metadata:
      labels:
        app:  dataset-copier
    spec:
      containers:
      - name:  dataset-copier
        image:  eeacms/rsync:latest
        command: ["/bin/sh", "-c", "rsync -Prcvv /mnt/rtdenoise_dataset/ /mnt/fast_denoise_dataset/ && sleep 99999999"]
        resources:
          requests:
            cpu: 32
            memory: 144Gi
          limits:
            cpu: 32
            memory: 144Gi
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset/
          name: rtdenoise-dataset
        - mountPath: /mnt/fast_denoise_dataset/
          name: fast-denoise-dataset
      volumes:
          - name: rtdenoise-dataset
            persistentVolumeClaim:
              claimName: rtdenoise-dataset
          - name: fast-denoise-dataset
            persistentVolumeClaim:
              claimName: fast-denoise-dataset


