apiVersion: apps/v1
kind: Deployment
metadata:
  name:  infinigen-reformat
  labels:
    app:  infinigen-reformat
spec:
  selector:
    matchLabels:
      app: infinigen-reformat
  replicas: 1
  template:
    metadata:
      labels:
        app:  infinigen-reformat
    spec:
      containers:
      - name:  infinigen-reformat
        image:  saadam1n/rfmt
        command: ["/bin/sh", "-c", "python3 -u ./script.py /mnt/dataset/basic/ /mnt/rtdenoise_dataset/ 0.5 && sleep 9999999"]
        resources:
          requests:
            cpu: 32
            memory: 144Gi
          limits:
            cpu: 32
            memory: 144Gi
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset/
          name: rtdenoise-dataset
        - mountPath: /mnt/dataset/
          name: rtdenoise-training-dataset
      volumes:
          - name: rtdenoise-dataset
            persistentVolumeClaim:
              claimName: rtdenoise-dataset
          - name: rtdenoise-training-dataset
            persistentVolumeClaim:
              claimName: rtdenoise-training-dataset


