apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dataset-downloader
  labels:
    app:  dataset-downloader
spec:
  selector:
    matchLabels:
      app: dataset-downloader
  replicas: 1
  template:
    metadata:
      labels:
        app:  dataset-downloader
    spec:
      containers:
      - name:  dataset-downloader
        image:  saadam1n/dataset_downloader
        command: ["/bin/sh", "-c", "python3 -u ./script.py /mnt/rtdenoise_dataset_tar_filtered/ /mnt/rtdenoise_dataset_tar_filtered_mini/ 0.013 0.1 1.0 && sleep 9999999"]
        resources:
          requests:
            cpu: 64
            memory: 144Gi
          limits:
            cpu: 64
            memory: 144Gi
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset_tar_filtered/
          name: rtdenoise-dataset-tar-filtered
        - mountPath: /mnt/rtdenoise_dataset_tar_filtered_mini/
          name: rtdenoise-dataset-tar-filtered-mini
      volumes:
          - name: rtdenoise-dataset-tar-filtered
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-tar-filtered
          - name: rtdenoise-dataset-tar-filtered-mini
            persistentVolumeClaim:
              claimName: rtdenoise-dataset-tar-filtered-mini


