apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dataset-copier-no-rsync
  labels:
    app:  dataset-copier-no-rsync
spec:
  selector:
    matchLabels:
      app: dataset-copier-no-rsync
  replicas: 1
  template:
    metadata:
      labels:
        app:  dataset-copier-no-rsync
    spec:
      nodeSelector:
        nautilus.io/network: "100000"  
      containers:
      - name:  dataset-copier-no-rsync
        image:  saadam1n/ihatersync
        command: ["/bin/sh", "-c", "python3 -u ./script.py /mnt/rtdenoise_dataset/ /mnt/fast_denoise_dataset/ && echo Freaking finished && sleep 99999999"]
        resources:
          requests:
            cpu: 64
            memory: 96Gi
          limits:
            cpu: 64
            memory: 96Gi
        volumeMounts:
        - mountPath: /mnt/rtdenoise_dataset/
          name: rtdenoise-dataset
        - mountPath: /mnt/fast_denoise_dataset/
          name: fast-denoise-dataset
      volumes:
          - name: rtdenoise-dataset
            persistentVolumeClaim:
              claimName: rtdenoise-dataset
          - name: fast-denoise-dataset
            persistentVolumeClaim:
              claimName: fast-denoise-dataset


