apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-denoise-dataset
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Ti
