apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtdenoise-temp-upload-vol3
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Ti
